// LumenCite Chat — sample sessions, messages, tool calls

const CHAT_SESSIONS = [
  {
    id: 1, title: "量子ウォークの研究まとめ",
    provider: "anthropic", model: "claude-sonnet-4.5",
    scope_mode: "entries", entry_count: 3,
    entries: [
      { id: 41, short: "Aharonov 1993", full: "Aharonov, Davidovich, Zagury (1993) — Quantum random walks" },
      { id: 88, short: "Kempe 2003", full: "Kempe (2003) — Quantum random walks: an introductory overview" },
      { id: 132, short: "Childs 2010", full: "Childs (2010) — Universal computation by quantum walk" },
    ],
    updated: "2h ago", active: true, messages: 12,
  },
  {
    id: 2, title: "Transformer 系の輪読会レジュメ整理",
    provider: "anthropic", model: "claude-sonnet-4.5",
    scope_mode: "entries", entry_count: 8,
    updated: "yesterday", messages: 24,
  },
  {
    id: 3, title: "Diffusion と Score Matching の関係",
    provider: "openai", model: "gpt-5",
    scope_mode: "entries", entry_count: 4,
    updated: "3 days ago", messages: 18,
  },
  {
    id: 4, title: "文献整理：未読の重要度ランキング",
    provider: "anthropic", model: "claude-haiku-4.5",
    scope_mode: "all",
    updated: "Nov 14", messages: 7,
  },
  {
    id: 5, title: "LoRA・PEFT 系まとめ（修論章 §3.2 向け）",
    provider: "anthropic", model: "claude-sonnet-4.5",
    scope_mode: "entries", entry_count: 11,
    updated: "Nov 9", messages: 31,
  },
  {
    id: 6, title: "RLHF と Constitutional AI の比較",
    provider: "openai", model: "gpt-5",
    scope_mode: "entries", entry_count: 5,
    updated: "Nov 2", messages: 14,
  },
  {
    id: 7, title: "Adam・最適化アルゴリズムの系譜",
    provider: "anthropic", model: "claude-haiku-4.5",
    scope_mode: "entries", entry_count: 6,
    updated: "Oct 28", messages: 9,
  },
  {
    id: 8, title: "Bishop PRML 第8章 — グラフィカルモデル",
    provider: "anthropic", model: "claude-sonnet-4.5",
    scope_mode: "entries", entry_count: 1,
    updated: "Oct 21", messages: 22,
  },
];

// Messages for the active session (#1).
// Tool call states: pending | running | done_collapsed | done_expanded | needs_approval | rejected
const CHAT_MESSAGES = [
  {
    id: 1, role: "user",
    content: "選択した3本に共通する考え方は何ですか？基本的な定式化と、応用先の違いを整理して教えてください。",
  },
  {
    id: 2, role: "assistant",
    md: [
      { kind: "p", html: "3本に共通するのは、<strong>離散時間量子ウォーク</strong>を「位置空間 × コイン空間」のテンソル積ヒルベルト空間で定式化することです。基本構造は次の通り：" },
      { kind: "tools", calls: [
        { state: "done_collapsed", kind: "read", tool: "fulltext_search",
          args: { query: "quantum walk Hilbert space", scope: "session" },
          summary: '"quantum walk Hilbert space" — 7 hits across 3 papers',
        },
        { state: "done_expanded", kind: "read", tool: "fulltext_search",
          args: { query: "coin operator definition", scope: "session" },
          summary: '"coin operator definition" — 4 hits',
          hits: [
            { entry: "Kempe 2003", page: 4,
              snippet: "We define the <em>coin operator</em> C acting on H_c. The unitary step is then U = S · (I ⊗ C), where S is the shift operator on H_p." },
            { entry: "Aharonov 1993", page: 2,
              snippet: "...replacing the classical coin flip with a unitary <em>coin operator</em>, yielding interference between paths of equal length." },
            { entry: "Childs 2010", page: 8,
              snippet: "For continuous-time walks we drop the coin; the walk is generated by a Hamiltonian H equal to the graph's adjacency matrix." },
            { entry: "Kempe 2003", page: 11,
              snippet: "The Hadamard <em>coin operator</em> C = H induces a quasi-uniform distribution over the line after n steps with variance Θ(n²)." },
          ],
        },
      ]},
      { kind: "math_display", tex: "\\mathcal{H} \\;=\\; \\mathcal{H}_p \\otimes \\mathcal{H}_c, \\qquad U \\;=\\; S \\cdot (I \\otimes C)",
        render: "𝓗 = 𝓗ₚ ⊗ 𝓗_c,        U = S · (I ⊗ C)", tag: "(1)" },
      { kind: "p", html: "ここで <span class=\"math-inline\">S</span> はコイン状態に応じて位置を ±1 ずらすシフト演算子、<span class=\"math-inline\">C</span> はコイン空間上のユニタリ（典型的には Hadamard）です<span class=\"citation\">¹</span>。<strong>古典ランダムウォークとの差は分散の指数だけ</strong>変わる点にあり、" },
      { kind: "math_display", tex: "\\operatorname{Var}[X_n] \\;\\sim\\; n^2 \\quad \\text{(量子)} \\;\\;\\text{vs.}\\;\\; n \\quad \\text{(古典)}",
        render: "Var[X_n] ∼ n²  (量子)   vs.   n  (古典)", tag: "(2)" },
      { kind: "p", html: "という二次加速が、これら3本の議論の出発点です<span class=\"citation\">²</span><span class=\"citation\">³</span>。" },
      { kind: "h", text: "応用先の違い" },
      { kind: "ul", items: [
        "<strong>Aharonov 1993</strong> — 物理側のモチベーション。中性子干渉・量子光学の文脈で、古典極限の取り方と <code>decoherence</code> の役割を強調。",
        "<strong>Kempe 2003</strong> — レビュー論文として、離散時間／連続時間の双方を一望し、混合時間・到達確率の解析手法を整理。",
        "<strong>Childs 2010</strong> — 計算理論側に振り、<em>glued trees</em> や <em>NAND tree</em> 評価で量子ウォークが BQP-完全であることを示す。",
      ]},
      { kind: "tools", calls: [
        { state: "done_collapsed", kind: "read", tool: "get_entry",
          args: { id: 132 },
          summary: "Childs (2010) — Universal computation by quantum walk",
        },
      ]},
      { kind: "p", html: "つまり3本は同じ枠組み（式 (1)）を共有しつつ、<strong>物理 → 数理レビュー → 計算複雑性</strong>と射程を広げています。次に何を深掘りしますか？" },
    ],
  },
  {
    id: 3, role: "user",
    content: "ありがとう。Childs 2010 にタグ `quantum-walk` を付けて、ノートに「応用: glued trees, NAND tree 評価」を追記しておいて。",
  },
  {
    id: 4, role: "assistant",
    md: [
      { kind: "p", html: "了解しました。タグ追加とノート追記を行います。" },
      { kind: "tools", calls: [
        { state: "done_collapsed", kind: "write", tool: "add_tag",
          args: { entry_id: 132, tag: "quantum-walk" },
          summary: "Childs (2010) に tag #quantum-walk を追加",
        },
        { state: "done_collapsed", kind: "write", tool: "update_notes",
          args: { entry_id: 132, mode: "append", text: "応用: glued trees, NAND tree 評価" },
          summary: "Childs (2010) のノートに 1 行追記",
        },
      ]},
      { kind: "p", html: "完了しました。Childs 2010 の詳細パネルに反映されています。" },
    ],
  },
  {
    id: 5, role: "user",
    content: "ついでにこの3本を Obsidian の「研究メモ」フォルダに今日の日付で1ファイルにまとめておいてほしい。あと Childs 2010 のタイトル末尾に「(STOC 2009)」を補ってサブタイトル化したい。",
  },
  {
    id: 6, role: "assistant",
    md: [
      { kind: "p", html: "2つの操作を提案します。<strong>承認が必要</strong>なものが含まれます。" },
      { kind: "tools", calls: [
        { state: "needs_approval", kind: "mcp", tool: "mcp_obsidian_create_note",
          server: "obsidian",
          args: {
            vault: "research",
            path: "研究メモ/2026-05-26 量子ウォーク3本まとめ.md",
            front_matter: { tags: ["quantum-walk", "lumencite"], source_session: 1 },
            body: "# 量子ウォーク3本まとめ\\n\\n- Aharonov 1993 …\\n- Kempe 2003 …\\n- Childs 2010 …",
          },
          summary: "Obsidian: research/研究メモ/2026-05-26 量子ウォーク3本まとめ.md を作成",
        },
        { state: "needs_approval", kind: "approve", tool: "update_entry",
          args: { id: 132, fields: { title: "Universal computation by quantum walk (STOC 2009)" } },
          summary: "Childs (2010) のタイトルを更新",
          diff: [
            { op: "-", text: "Universal computation by quantum walk" },
            { op: "+", text: "Universal computation by quantum walk (STOC 2009)" },
          ],
        },
      ]},
    ],
    blocking: true,  // composer disabled until resolved
  },
];

// Search hit suggestion when scope picker is open
const SCOPE_LIB_ENTRIES = [
  { id: 41,  short: "Aharonov 1993", full: "Quantum random walks", year: 1993, picked: true },
  { id: 88,  short: "Kempe 2003",    full: "Quantum random walks: an introductory overview", year: 2003, picked: true },
  { id: 132, short: "Childs 2010",   full: "Universal computation by quantum walk", year: 2010, picked: true },
  { id: 1,   short: "Vaswani 2017",  full: "Attention Is All You Need", year: 2017, picked: false },
  { id: 7,   short: "Ho 2020",       full: "Denoising Diffusion Probabilistic Models", year: 2020, picked: false },
  { id: 20,  short: "Hu 2022",       full: "LoRA: Low-Rank Adaptation of Large Language Models", year: 2022, picked: false },
];

window.LUMEN_CHAT = { CHAT_SESSIONS, CHAT_MESSAGES, SCOPE_LIB_ENTRIES };
